/**
 * CoachingRunItem Model — Coach M1
 *
 * Stores individual coaching items (strengths, issues, suggestions, questions)
 * generated by a coaching run. Items are ordered within their category and run.
 * Once a run completes, items are immutable advisory history.
 */

import {
  DataTypes,
  Model,
  type InferAttributes,
  type InferCreationAttributes,
  type CreationOptional,
  type ForeignKey,
  type NonAttribute,
  type HasManyGetAssociationsMixin,
  type BelongsToGetAssociationMixin,
  type Sequelize,
} from 'sequelize';

export type CoachingItemCategory = 'strength' | 'issue' | 'suggestion' | 'question';

class CoachingRunItem extends Model<
  InferAttributes<CoachingRunItem>,
  InferCreationAttributes<CoachingRunItem>
> {
  declare id: CreationOptional<string>;
  declare run_id: ForeignKey<string>;
  declare category: CoachingItemCategory;
  declare position: number;
  declare text: string;
  declare created_at: CreationOptional<Date>;

  // Association mixins
  declare getReferences: HasManyGetAssociationsMixin<import('./coaching_run_reference').CoachingRunReference>;
  declare references?: NonAttribute<import('./coaching_run_reference').CoachingRunReference[]>;

  declare getRun: BelongsToGetAssociationMixin<import('./coaching_run').CoachingRun>;
  declare run?: NonAttribute<import('./coaching_run').CoachingRun>;

  static associate(models: Record<string, any>) {
    this.belongsTo(models.CoachingRun, {
      foreignKey: 'run_id',
      as: 'run',
      onDelete: 'CASCADE',
    });

    if (models.CoachingRunReference) {
      this.hasMany(models.CoachingRunReference, {
        foreignKey: 'item_id',
        as: 'references',
        onDelete: 'CASCADE',
      });
    }
  }
}

export default (sequelize: Sequelize) => {
  CoachingRunItem.init(
    {
      id: {
        type: DataTypes.UUID,
        primaryKey: true,
        defaultValue: DataTypes.UUIDV4,
      },
      run_id: {
        type: DataTypes.UUID,
        allowNull: false,
        references: { model: 'coaching_runs', key: 'id' },
      },
      category: {
        type: DataTypes.STRING(20),
        allowNull: false,
        validate: {
          isIn: [['strength', 'issue', 'suggestion', 'question']],
        },
      },
      position: {
        type: DataTypes.INTEGER,
        allowNull: false,
      },
      text: {
        type: DataTypes.TEXT,
        allowNull: false,
      },
      created_at: {
        type: DataTypes.DATE,
        allowNull: false,
        defaultValue: sequelize.literal('CURRENT_TIMESTAMP'),
      },
    },
    {
      tableName: 'coaching_run_items',
      underscored: true,
      timestamps: false,
      sequelize,
    },
  );

  return CoachingRunItem;
};

export type { CoachingRunItem };
