/**
 * Discovery Application Service — PLAT-3 + DISC-1
 *
 * Extracted from discoverHandler.ts
 * Orchestrates discovery research workflows: document processing,
 * privacy gating, YAML template processing, cascade variable extraction,
 * and discovery folder scaffolding.
 *
 * DISC-1 integration:
 * - DiscoveryRun created BEFORE long-running analysis (locked decision A)
 * - EvidenceSource created for each uploaded document
 * - DiscoveryArtifact created with canonical content (locked decision D)
 * - GitHub is projection, not canonical
 */

import type { ApplicationContext } from '../types/application-context';
import { format } from 'date-fns';
import { assertProjectAccessByActor } from '../services/authorization.service';
import { getProjectById } from '../services/project.service';
import { loadDiscoveryArtifacts, type DiscoveryArtifact } from '../helpers/discoveryLoader';
import { getConfigRepo, YAML_TEMPLATE_PATH, fetchFileFromRepo, createOrUpdateFileOnGitHub, fetchFileFromRepoByPath } from '../helpers/github';
import { processYamlTemplate, extractAndPersistDiscoveryVariables, type DryRunResult, type ExtractionOutcome } from '../helpers/yamlProcessor';
import type { EmitSpec } from '../helpers/variableExtractor';
import { parseDocuments, validateDocuments } from '../helpers/documentParser';
import type { VariableContext } from '../helpers/studyVariables';
import yaml from 'js-yaml';
import { authorizeForModel, scanForPii } from '../services/content-governance.service';
import * as runService from '../services/discovery-run.service';
import * as artifactService from '../services/discovery-artifact.service';
import * as evidenceService from '../services/evidence-source.service';
import type { DiscoveryType } from '../database/models/discovery_run';
import sequelize from '../database';

// ─── Input/Output Types ──────────────────────────────────────────

export type DiscoveryTypeKey = 'desk_research' | 'stakeholder_synthesis' | 'survey_synthesis';

export interface DiscoveryInput {
  /** Project context */
  projectId: number;
  projectSlug: string;

  /** Discovery type */
  discoveryType: DiscoveryTypeKey;

  /** Form fields */
  topic: string;
  description: string | null;

  /** Processed document content (already extracted from files) */
  documents: DocumentInput[];

  /** Actor info */
  createdByActorId: string;

  /** Survey-specific fields */
  surveyName?: string;
  questionFocus?: string;
}

export interface DocumentInput {
  name: string;
  content: string;
  type: string;
  size: number;
  [key: string]: unknown;
}

export interface DiscoveryResult {
  /** URL of the generated artifact on GitHub */
  url: string;
  /** Topic slug used */
  topicSlug: string;
  /** Discovery type label */
  typeLabel: string;
  /** Cascade extraction outcome */
  extractionSuccess: boolean;
  extractionVariableCount: number;
  /** DISC-1: DiscoveryRun public ID */
  runPublicId?: string;
  /** DISC-1: DiscoveryArtifact public ID */
  artifactPublicId?: string;
}

export interface DiscoveryArtifactInfo {
  slug: string;
  type: string;
  label: string;
  date: string;
  icon: string;
  variableCount: number;
}

export interface PrivacyViolation {
  label: string;
  snippet: string;
}

// ─── Constants ──────────────────────────────────────────────────

interface DiscoveryTypeConfig {
  yaml: string;
  type: string;
  fileSlug: string;
  label: string;
}

const DISCOVERY_TYPES: Record<DiscoveryTypeKey, DiscoveryTypeConfig> = {
  desk_research: {
    yaml: 'desk_research.yaml',
    type: 'desk-research',
    fileSlug: 'desk-research',
    label: 'Desk research',
  },
  stakeholder_synthesis: {
    yaml: 'stakeholder_synthesis.yaml',
    type: 'stakeholder-interviews',
    fileSlug: 'stakeholder-synthesis',
    label: 'Stakeholder synthesis',
  },
  survey_synthesis: {
    yaml: 'survey_synthesis.yaml',
    type: 'survey-synthesis',
    fileSlug: 'survey-synthesis',
    label: 'Survey synthesis',
  },
};

const DISCOVERY_README = `# Discovery Research

Pre-study discovery research that informs briefs and accumulates as organizational memory.

## Contents

Discovery artifacts are stored directly in this folder.

*Generated by Qori*
`;

// ─── Helpers ────────────────────────────────────────────────────

function slugifyTopic(topic: string): string {
  return topic
    .toLowerCase()
    .replace(/[_\s]+/g, '-')
    .replace(/[^a-z0-9-]/g, '')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');
}

async function scaffoldDiscoveryFolders(projectSlug: string): Promise<void> {
  const readmePath = `${projectSlug}/00-discovery/README.md`;
  try {
    await fetchFileFromRepoByPath(process.env.GITHUB_REPO!, readmePath);
    return;
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    const status = (error as Record<string, unknown>)?.status;
    if (status === 404 || message?.includes('Not Found') || message?.includes('Could not fetch file')) {
      await createOrUpdateFileOnGitHub(readmePath, DISCOVERY_README);
    }
  }
}

// ─── List Discovery Artifacts ───────────────────────────────────

export async function listDiscoveryArtifacts(
  ctx: ApplicationContext,
  projectId: number,
): Promise<DiscoveryArtifactInfo[]> {
  await assertProjectAccessByActor(ctx.actor.id, projectId, ctx.organization.id);

  const artifacts = await loadDiscoveryArtifacts(projectId);
  return artifacts.map((a: DiscoveryArtifact) => ({
    slug: a.slug,
    type: a.type,
    label: a.label,
    date: a.date,
    icon: a.icon,
    variableCount: a.variableCount,
  }));
}

// ─── Main Orchestration ─────────────────────────────────────────

export async function executeDiscovery(
  ctx: ApplicationContext,
  input: DiscoveryInput,
): Promise<DiscoveryResult> {
  // Authorization
  await assertProjectAccessByActor(ctx.actor.id, input.projectId, ctx.organization.id);

  const typeConfig = DISCOVERY_TYPES[input.discoveryType];
  if (!typeConfig) {
    throw new Error(`Unknown discovery type: ${input.discoveryType}`);
  }

  if (!input.topic || !slugifyTopic(input.topic)) {
    throw new Error('Topic must contain alphanumeric characters');
  }

  if (input.documents.length === 0) {
    throw new Error('At least one document is required');
  }

  let topicSlug = slugifyTopic(input.topic);

  // Validate documents
  const validation = validateDocuments(input.documents);
  if (!validation.isValid) {
    throw new Error(validation.message);
  }

  // Check for duplicate filename
  const dateIso = format(new Date(), 'yyyy-MM-dd');
  const expectedFilename = `${topicSlug}-${typeConfig.fileSlug}-${dateIso}.md`;
  const expectedPath = `${input.projectSlug}/00-discovery/${expectedFilename}`;
  try {
    await fetchFileFromRepoByPath(process.env.GITHUB_REPO!, expectedPath);
    const timeSuffix = format(new Date(), 'HHmm');
    topicSlug = `${topicSlug}-${timeSuffix}`;
  } catch {
    // File doesn't exist — proceed
  }

  // Load project for problem_statement
  const project = await getProjectById(input.projectId);
  const projectProblemStatement = project?.problem_statement || null;

  // ═══════════════════════════════════════════════════════════════════════════
  // DISC-1: Create DiscoveryRun BEFORE long-running analysis (locked decision A)
  // ═══════════════════════════════════════════════════════════════════════════
  const run = await runService.createDiscoveryRun({
    projectId: input.projectId,
    discoveryType: input.discoveryType as DiscoveryType,
    topic: input.topic,
    topicSlug,
    sourceIntent: input.description,
    actorId: ctx.actor.id,
    createdByIdentity: `slack:${input.createdByActorId}`,
  });

  // ═══════════════════════════════════════════════════════════════════════════
  // DISC-1: Create EvidenceSource for each uploaded document
  // ═══════════════════════════════════════════════════════════════════════════
  const sources = await evidenceService.createDocumentSources(
    input.projectId,
    input.documents.map(d => ({
      name: d.name,
      content: d.content,
      type: d.type,
      size: d.size,
      slackFileId: (d as Record<string, unknown>).slackFileId as string | undefined,
    })),
    input.createdByActorId,
  );

  // Associate sources with run
  await runService.associateSources({
    runId: run.id,
    sourceIds: sources.map(s => s.id),
  });

  // Mark run as processing
  await runService.startDiscoveryRun(run.id);

  // Scaffold discovery folders
  await scaffoldDiscoveryFolders(input.projectSlug);

  // Parse documents
  const parsedDocuments = parseDocuments(input.documents);
  const formattedDocumentContent: string = parsedDocuments.structured_format;

  const MIME_LABELS: Record<string, string> = {
    'application/pdf': 'PDF',
    'text/plain': 'Text',
    'text/markdown': 'Markdown',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document': 'Word',
    'application/msword': 'Word',
  };

  const documentNames = input.documents.map(d => d.name);
  const documentTypes = input.documents.map(d => MIME_LABELS[d.type] || d.type);

  // Privacy gate
  const privacyResult = authorizeForModel(
    formattedDocumentContent,
    'DISCOVERY_UPLOAD',
    { projectId: input.projectId, sourceId: `discovery:${input.discoveryType}:${topicSlug}` },
  );

  if (privacyResult.status === 'pending_review') {
    const piiFindings = scanForPii(formattedDocumentContent);
    // Mark run as failed before throwing
    await runService.failDiscoveryRun(run.id, 'PRIVACY_VIOLATION', 'PII detected in documents', 'privacy_scan');
    throw new PrivacyError(
      'Privacy scan detected potential PII in uploaded files',
      piiFindings.map((f: { label: string; snippet: string }) => ({ label: f.label, snippet: f.snippet })),
    );
  }

  if (privacyResult.status === 'denied') {
    await runService.failDiscoveryRun(run.id, 'CONTENT_DENIED', privacyResult.reason || 'Unknown', 'content_auth');
    throw new Error(`Content authorization failed: ${privacyResult.reason}`);
  }

  // Build template data
  const data: Record<string, unknown> = {
    topic: input.topic,
    effective_topic: input.topic,
    topic_slug: topicSlug,
    project_slug: input.projectSlug,
    project_problem_statement: projectProblemStatement,
    source_intent: input.description,
    description: input.description || input.topic,
    document_content: privacyResult.modelSafeContent!,
    combined_file_content: privacyResult.modelSafeContent!,
    _discovery_type: typeConfig.type,
    selected_study: `discovery-${topicSlug}`,
    study_name: input.topic,
    document_count: input.documents.length,
    document_names: documentNames,
    document_types: documentTypes,
  };

  // Survey-specific fields
  if (input.discoveryType === 'survey_synthesis') {
    data.survey_name = input.surveyName;
    data.question_focus = input.questionFocus || '';
  }

  // Stakeholder-specific fields
  if (input.discoveryType === 'stakeholder_synthesis') {
    data.researcher_contact = input.createdByActorId;
    data.detected_files = input.documents.map(d => d.name).join('\n- ');
    data.file_list = input.documents.map(d => d.name);
  }

  // Artifact identity context
  let contentFingerprint = 'unknown';
  try {
    const { computeContentHash } = require('../helpers/survey');
    contentFingerprint = computeContentHash(privacyResult.modelSafeContent!).substring(0, 16);
  } catch {
    // Fallback if survey module not available
  }
  data.__artifactContext = {
    projectId: input.projectId,
    studyId: null,
    artifactType: 'discovery',
    title: `${input.discoveryType.replace(/_/g, ' ')} — ${input.topic}`,
    canonicalUpstreamInputs: [`content:${contentFingerprint}`],
    createdBy: input.createdByActorId,
  };

  // ═══════════════════════════════════════════════════════════════════════════
  // DISC-1: Structured pipeline with canonical artifact lineage
  //
  // Order of operations (per DISC-1 locked decisions):
  // 1. Fetch YAML template and parse to get emits spec
  // 2. Call processYamlTemplate with dryRun=true (AI generation, no write/extract)
  // 3. Create DiscoveryArtifact with canonical content (decision D: Postgres canonical)
  // 4. Write to GitHub (projection only)
  // 5. Extract variables with artifact FK (canonical lineage)
  // 6. Finalize artifact and complete run
  // ═══════════════════════════════════════════════════════════════════════════
  let artifact;
  try {
    // 1. Fetch and parse YAML template to get emits spec
    const file = await fetchFileFromRepo(getConfigRepo(), YAML_TEMPLATE_PATH, typeConfig.yaml);
    const yamlConfig = yaml.load(file.content) as {
      id?: string;
      version?: string;
      emits?: EmitSpec[];
    } | null;

    if (!yamlConfig) {
      throw new Error(`Failed to parse YAML template: ${typeConfig.yaml}`);
    }

    const templateVersion = yamlConfig.version || null;
    const emitsSpec: EmitSpec[] = yamlConfig.emits || [];

    // 2. Process YAML with dryRun=true - AI generation only, no GitHub write or extraction
    const variableContext: VariableContext = {
      projectId: input.projectId,
    };

    const dryRunResult = await processYamlTemplate(
      file.content, data, '', '', false, variableContext, undefined, true,
    );

    // 3. Create DiscoveryArtifact with canonical content BEFORE GitHub projection
    //    Per locked decision D: GitHub is projection, not canonical
    artifact = await artifactService.createDiscoveryArtifact({
      projectId: input.projectId,
      discoveryRunId: run.id,
      artifactType: input.discoveryType.replace('_synthesis', '_synthesis') as 'desk_research' | 'stakeholder_synthesis' | 'survey_synthesis' | 'cross_source_synthesis',
      title: `${typeConfig.label}: ${input.topic}`,
      topicSlug,
      canonicalContent: dryRunResult.outputTemplate || null,
      templateName: typeConfig.yaml.replace('.yaml', ''),
      templateVersion,
      derivationFingerprint: contentFingerprint,
      actorId: ctx.actor.id,
      generatedByIdentity: `slack:${input.createdByActorId}`,
    });

    // 4. Write to GitHub (projection) - this happens AFTER artifact exists
    let githubResult: { path: string; sha: string; url: string };
    try {
      githubResult = await createOrUpdateFileOnGitHub(dryRunResult.path, dryRunResult.content);

      // Record projection metadata on artifact
      await artifactService.recordProjection(artifact.id, {
        githubPath: githubResult.path,
        githubSha: githubResult.sha,
      });
    } catch (githubError) {
      // GitHub projection failure is non-blocking for canonical pipeline
      // The artifact and its content are canonical in Postgres
      const githubMsg = githubError instanceof Error ? githubError.message : String(githubError);
      console.warn(`⚠️ GitHub projection failed (non-blocking): ${githubMsg}`);
      // Use synthetic result for return value
      githubResult = {
        path: dryRunResult.path,
        sha: 'projection-failed',
        url: `https://github.com/${process.env.GITHUB_OWNER}/${process.env.GITHUB_REPO}/blob/main/${dryRunResult.path}`,
      };
    }

    // 5. Extract variables with artifact FK for canonical lineage
    //    This happens AFTER artifact creation so FK is available
    let extractionSuccess = true;
    let extractionVariableCount = 0;

    if (emitsSpec.length > 0) {
      const extractResult = await extractAndPersistDiscoveryVariables({
        templateId: yamlConfig.id || typeConfig.yaml.replace('.yaml', ''),
        templateVersion: templateVersion || '',
        emitsSpec,
        outputTemplate: dryRunResult.outputTemplate,
        inputValues: data,
        variableContext,
        discoveryArtifactFkId: artifact.id, // DISC-1: Canonical relational FK
      });

      extractionSuccess = extractResult.success;
      extractionVariableCount = extractResult.variableCount || 0;

      if (!extractResult.success) {
        // Don't fail the entire run for extraction failure — artifact is still valid
        console.warn(`⚠️ Cascade variable extraction failed: ${extractResult.error}`);
      } else {
        console.log(`✅ Variables extracted with artifact FK ${artifact.id}: ${extractionVariableCount} items`);
      }
    }

    // 6. Finalize artifact (mark as current, supersede previous if any)
    await artifactService.finalizeArtifactSupersession(artifact.id);

    // Mark run as completed
    await runService.completeDiscoveryRun(run.id);

    return {
      url: githubResult.url,
      topicSlug,
      typeLabel: typeConfig.label,
      extractionSuccess,
      extractionVariableCount,
      runPublicId: run.public_id,
      artifactPublicId: artifact.public_id,
    };
  } catch (error) {
    // Mark run as failed
    const errorMessage = error instanceof Error ? error.message : String(error);
    await runService.failDiscoveryRun(
      run.id,
      'GENERATION_ERROR',
      errorMessage.substring(0, 500),
      'yaml_processing',
    );

    // Mark artifact as failed if it was created
    if (artifact) {
      await artifactService.markArtifactFailed(artifact.id);
    }

    throw error;
  }
}

// ─── Privacy Error ──────────────────────────────────────────────

export class PrivacyError extends Error {
  public readonly findings: PrivacyViolation[];

  constructor(message: string, findings: PrivacyViolation[]) {
    super(message);
    this.name = 'PrivacyError';
    this.findings = findings;
  }
}
